ALTER TABLE "Product"
ADD COLUMN IF NOT EXISTS "slug" TEXT,
ADD COLUMN IF NOT EXISTS "badges" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN IF NOT EXISTS "material" TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS "fabric" TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS "fit" TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS "careInstructions" TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS "countryOfOrigin" TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS "metaTitle" TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS "metaDescription" TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS "metaKeywords" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN IF NOT EXISTS "rating" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS "reviewCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS "reviews" JSONB NOT NULL DEFAULT '[]';

CREATE UNIQUE INDEX IF NOT EXISTS "Product_slug_key" ON "Product"("slug");
